# 1panel集成的docker-compose覆盖配置示例
# 
# 使用方法：
# 1. 将此文件重命名为 docker-compose.override.yml
# 2. 根据您的1panel证书路径调整volumes配置
# 3. 如果使用1panel反向代理，可以注释掉端口映射

services:
  derp:
    volumes:
      # 1panel证书挂载示例 - 请根据实际路径调整
      # 替换 'your-domain.com' 为您的实际域名
      - /opt/1panel/data/apps/openresty/ssl/your-domain.com:/certs:ro
      
      # 或者如果您使用其他证书路径，例如：
      # - /path/to/your/certificates:/certs:ro
    
    # 如果您使用1panel的OpenResty进行反向代理，
    # 可以注释掉以下端口映射，只保留STUN端口
    ports:
      - "80:80"      # HTTP端口 - 1panel代理时可以注释
      - "443:1443"   # HTTPS端口 - 1panel代理时可以注释  
      - "3478:3478/udp"  # STUN端口 - 必须保留
    
    # 可选：如果需要特定的网络配置
    # networks:
    #   - 1panel_network

# 可选：如果使用1panel的网络
# networks:
#   1panel_network:
#     external: true