services:
  derp:
    image: hewenyulucky/derp:latest
    container_name: derp
    env_file:
      - .env
    ports:
      - "3478:3478" # STUN 端口
    volumes:
      - ./derp/config:/var/lib/tailscale

  openresty:
    image: openresty/openresty:1.21.4.1-focal
    container_name: netdns-domestic-openresty
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./openresty/conf.d:/etc/nginx/conf.d:ro
      - ./openresty/ssl:/etc/openresty/ssl:ro
      - ./certbot/www:/var/www/certbot:ro # 用于ACME http-01 质询
    depends_on:
      - derp
