services:
  derp:
    image: hewenyulucky/derp:latest
    container_name: derp
    restart: always
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "80:80"
      - "443:1443"
      - "3478:3478/udp"
    volumes:
      - /lib/modules:/lib/modules:ro
      - ./derp/config:/var/lib/tailscale
      - ./certs:/certs:ro  # 1panel证书目录挂载
    devices:
      - /dev/net/tun:/dev/net/tun
